# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 20, 131, 61))

        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)

        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")

        self.usr_name = QtWidgets.QLineEdit(self.centralwidget)
        self.usr_name.setGeometry(QtCore.QRect(250, 160, 181, 21))
        self.usr_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.usr_name.setObjectName("usr_name")

        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(290, 340, 75, 23))
        self.btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn.setObjectName("btn")
        self.btn.clicked.connect(self.on_click)

        self.passwd = QtWidgets.QLineEdit(self.centralwidget)
        self.passwd.setGeometry(QtCore.QRect(240, 270, 201, 21))
        self.passwd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.passwd.setObjectName("passwd")

        self.usrnam_lable = QtWidgets.QLabel(self.centralwidget)
        self.usrnam_lable.setGeometry(QtCore.QRect(290, 110, 101, 31))

        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)

        self.usrnam_lable.setFont(font)
        self.usrnam_lable.setStyleSheet("color: rgb(255, 255, 255);")
        self.usrnam_lable.setObjectName("usrnam_lable")

        self.passwd_lable = QtWidgets.QLabel(self.centralwidget)
        self.passwd_lable.setGeometry(QtCore.QRect(290, 220, 101, 31))

        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)

        self.passwd_lable.setFont(font)
        self.passwd_lable.setStyleSheet("color: rgb(255, 255, 255);")
        self.passwd_lable.setObjectName("passwd_lable")
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Login Form"))
        self.usr_name.setPlaceholderText(_translate("MainWindow", "Enter Your Username"))
        self.btn.setText(_translate("MainWindow", "Login"))
        self.passwd.setPlaceholderText(_translate("MainWindow", "Enter Your Username"))
        self.usrnam_lable.setText(_translate("MainWindow", "  Username"))
        self.passwd_lable.setText(_translate("MainWindow", " Password"))
    
    def on_click(self):
        dg_box = QMessageBox(MainWindow)
        dg_box.setText("You are loged in")
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        dg_box.setWindowTitle("Loged in")
        dg_box.setFont(font)
        dg_box.setStyleSheet("color: rgb(255, 255, 255);")
        dg_box.exec_()
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
