from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.381, y1:0.539955, x2:0.551, y2:0.454545, stop:0 rgba(0, 255, 7, 255), stop:1 rgba(91, 38, 38, 255));\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.mlnm = QtWidgets.QLineEdit(self.centralwidget)
        self.mlnm.setGeometry(QtCore.QRect(10, 100, 113, 20))
        self.mlnm.setObjectName("mlnm")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.mc = QtWidgets.QLineEdit(self.centralwidget)
        self.mc.setGeometry(QtCore.QRect(180, 100, 113, 20))
        self.mc.setObjectName("mc")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.md = QtWidgets.QComboBox(self.centralwidget)
        self.md.setGeometry(QtCore.QRect(360, 100, 111, 22))
        self.md.setObjectName("md")
        self.md.addItem("")
        self.md.addItem("")
        self.md.addItem("")
        self.md.addItem("")
        self.md.addItem("")
        self.md.addItem("")
        self.md.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(530, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.mds = QtWidgets.QLineEdit(self.centralwidget)
        self.mds.setGeometry(QtCore.QRect(500, 100, 271, 111))
        self.mds.setObjectName("mds")
        self.meallist = QtWidgets.QListWidget(self.centralwidget)
        self.meallist.setGeometry(QtCore.QRect(150, 250, 411, 291))
        self.meallist.setObjectName("meallist")
        self.addmeal = QtWidgets.QPushButton(self.centralwidget)
        self.addmeal.setGeometry(QtCore.QRect(330, 200, 91, 41))
        self.addmeal.setObjectName("addmeal")
        self.addmeal.clicked.connect(self.add_meal_to_list)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Smart Meal Planner"))
        self.label_2.setText(_translate("MainWindow", "Meal Name"))
        self.label_3.setText(_translate("MainWindow", "Meal Catageory"))
        self.label_4.setText(_translate("MainWindow", "Meal Date"))
        self.md.setItemText(0, _translate("MainWindow", "Saturday"))
        self.md.setItemText(1, _translate("MainWindow", "SunDay"))
        self.md.setItemText(2, _translate("MainWindow", "Monday"))
        self.md.setItemText(3, _translate("MainWindow", "Tuesday"))
        self.md.setItemText(4, _translate("MainWindow", "Wednesday"))
        self.md.setItemText(5, _translate("MainWindow", "Thursday"))
        self.md.setItemText(6, _translate("MainWindow", "Friday"))
        self.label_5.setText(_translate("MainWindow", "Meal Discription"))
        self.addmeal.setText(_translate("MainWindow", "Add Meal"))
    
    def add_meal_to_list(self):
        meal_name = self.mlnm.text()
        meal_catageory = self.mc.text()
        meal_date = self.md.currentText()
        meal_des = self.mds.text()
        info = f"Meal Name: {meal_name}, Meal Catageory: {meal_catageory}, Meal Date: {meal_date}, Meal Description: {meal_des}"
        self.meallist.addItem(info)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
