# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogBoxui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(200, 220, 401, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn.setFont(font)
        self.btn.setObjectName("btn")
        self.btn.clicked.connect(self.show_msg_box)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def show_msg_box(self):
        dg_box = QMessageBox(MainWindow)
        dg_box.setText("U GOt Hacked haha!")
        dg_box.setWindowTitle("Alert")
        dg_box.setIcon(QMessageBox.Information)
        dg_box.setInformativeText("are u broke or something?")
        dg_box.setDetailedText("Bro everything will be fine don't worry")

        dg_box.setStandardButtons(QMessageBox.Ok|QMessageBox.Cancel|QMessageBox.Retry)
        dg_box.buttonClicked.connect(self.dg_clicked)
        dg_box.exec_()
        """
            Icons = Critical, Warning, Information, Question
        """

    def dg_clicked(self, dg_btn):
        print(dg_btn.text())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn.setText(_translate("MainWindow", "Click here and get 20 dollars"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
