# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.awtw = QtWidgets.QLineEdit(self.centralwidget)
        self.awtw.setGeometry(QtCore.QRect(10, 30, 113, 20))
        self.awtw.setObjectName("awtw")
        self.walab = QtWidgets.QLabel(self.centralwidget)
        self.walab.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.walab.setObjectName("walab")
        self.hmlab = QtWidgets.QLabel(self.centralwidget)
        self.hmlab.setGeometry(QtCore.QRect(10, 60, 131, 21))
        self.hmlab.setObjectName("hmlab")
        self.hmea = QtWidgets.QLineEdit(self.centralwidget)
        self.hmea.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.hmea.setObjectName("hmea")
        self.atlab = QtWidgets.QLabel(self.centralwidget)
        self.atlab.setGeometry(QtCore.QRect(10, 130, 131, 21))
        self.atlab.setObjectName("atlab")
        self.atwatch = QtWidgets.QLineEdit(self.centralwidget)
        self.atwatch.setGeometry(QtCore.QRect(10, 160, 113, 20))
        self.atwatch.setObjectName("atwatch")
        self.acwlab = QtWidgets.QLabel(self.centralwidget)
        self.acwlab.setGeometry(QtCore.QRect(280, 20, 141, 16))
        self.acwlab.setObjectName("acwlab")
        self.acw = QtWidgets.QLineEdit(self.centralwidget)
        self.acw.setGeometry(QtCore.QRect(270, 40, 113, 20))
        self.acw.setObjectName("acw")
        self.welab = QtWidgets.QLabel(self.centralwidget)
        self.welab.setGeometry(QtCore.QRect(280, 70, 131, 21))
        self.welab.setObjectName("welab")
        self.we = QtWidgets.QLineEdit(self.centralwidget)
        self.we.setGeometry(QtCore.QRect(270, 110, 113, 20))
        self.we.setObjectName("we")
        self.atlab2 = QtWidgets.QLabel(self.centralwidget)
        self.atlab2.setGeometry(QtCore.QRect(280, 140, 131, 21))
        self.atlab2.setObjectName("atlab2")
        self.atwatching = QtWidgets.QLineEdit(self.centralwidget)
        self.atwatching.setGeometry(QtCore.QRect(270, 170, 113, 20))
        self.atwatching.setObjectName("atwatching")
        self.wtwanimelist = QtWidgets.QListWidget(self.centralwidget)
        self.wtwanimelist.setGeometry(QtCore.QRect(0, 250, 411, 351))
        self.wtwanimelist.setObjectName("wtwanimelist")
        self.cwalist = QtWidgets.QListWidget(self.centralwidget)
        self.cwalist.setGeometry(QtCore.QRect(420, 250, 381, 351))
        self.cwalist.setObjectName("cwalist")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 210, 121, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(520, 210, 151, 41))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.walab.setText(_translate("MainWindow", "Anime wnat to watch"))
        self.hmlab.setText(_translate("MainWindow", "how many ep in the anime"))
        self.atlab.setText(_translate("MainWindow", "Anime Type"))
        self.acwlab.setText(_translate("MainWindow", "Anime currently watching"))
        self.welab.setText(_translate("MainWindow", "which Episode"))
        self.atlab2.setText(_translate("MainWindow", "Anime Type"))
        self.label_7.setText(_translate("MainWindow", "want to watch anime list"))
        self.label_8.setText(_translate("MainWindow", "currently watching anime list"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
